### ISSUE TITLE
Reset on get request

### ISSUE THREAD

**Issue by ndjdev** [stephrdev/django-formwizard#7]
I can't get my head around why you would want to force reset on every process_get_request, rather than let the developer decide whether they wanted to reset or not. Consider the scenario - I override process_request to interpret some slug information in the URL. After using the slug to retrieve an object, I update_extra_context with that object so it can be embedded in the first page of the form. Except process_get_request then resets the wizard making everything above useless. I've used this project 3 times now and every time I've had to override process_get_request as well. Am I just doing it wrong?!

**Comment by ndjdev** [comment]
OK I've got it working by attaching the object to kwargs after reading through the code, but I have another scenario which I believe makes the forced resets counter-productive (including the last one on 'done'). Consider a booking system where the user has to enter a lot of data and at the end, 'done' needs to bounce to a payment system. If the payment fails and the user is given a "try again" link, that is going to process_get_request on the first page. Without manual control over resets, this data will have been deleted, whereas it would make more sense to allow the developer to call reset in the case of a successful transaction.

**Comment by stephrdev** [comment]
The idea behind the reset is documented in the docstring of the process_get_request method:

If the wizard gets a GET request, it assumes that the user just
starts at the first step or wants to restart the process. The wizard
will be resetted before rendering the first step.

You could just overwrite the reset_wizard method to decide whether or not the formwizard should reset the storage. There will be no duplicated code because reset_wizard just calls self.storage.reset by default.

Maybe this hint helps a bit ;-)

Cheers,

**Comment by ndjdev** [comment]
I know what the idea behind it is, I'm saying the idea is totally counterproductive to the effectiveness of the package. Surely one of the most useful things about having a session-based formwizard is that any multitude of errors can occur and the process can be resumed from the beginning at will. I'm not saying remove it altogether, just maybe add a reset=True parameter to process_get_request or something (incorporating zebuline's fork is a must as well).
